name: kpathshala
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  custom_button_builder: ^0.0.4
  font_awesome_flutter: ^10.7.0
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0
  pinput: ^5.0.0
  image_picker: ^1.1.2
  fui_kit: ^2.0.2
  http: ^1.2.2
  android_intent_plus: ^5.1.0
  device_info_plus: ^10.1.2
  gap: ^3.0.1
  url_launcher: ^6.3.0
  smooth_page_indicator: ^1.2.0+3
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  flutter_facebook_auth: ^7.0.1
  device_preview: ^1.2.0
  dio: ^5.6.0
  velocity_x: ^4.2.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
